METHOD:
  name_method: 'EM-PADDLE-ID'
  iter: 5
  beta: 1.2
  p: 1
  gamma_prox: 0.06
  zeta1: 0.05
  zeta2: 1.55
  kappa: 310
  omega1: 154
  omega2: 0.2
  auto_init: True
  acc_clustering: False
  tunable: False
  batch_fsolve_size: 16
  n_iter_prox : 200