METHOD:
  name_method: 'ICI'
  step: 5
  max_iter : 100
  reduce : "pca"  # in ["isomap", "ltsa", "mds", "lle", "se", "pca", "none"]
  d : 50
  C : 20
  classifier : lr # in ["lr", "svm"]
  iter : -1
  tunable : False
  acc_clustering : False