METHOD:
  name_method: 'MM_RPADDLE_REG'
  iter: 20
  lambd: 120
  lr : 0.1
  beta : 2.
  deg_reg_theta: 1
  kappa : 1
  change_theta_reg: False
  p: 2
  id_cov : True
  acc_clustering: False
  tunable: False
  plot: True
  temp: 10 # 50
  reg_inv: 0.