METHOD:
  name_method: 'RTIM_GD'
  temp: 10
  loss_weights: [1.0, 0.3, 1.0]  # [Xent, H(Y), H(Y|X)]
  lr_tim: 1e-4
  beta: 1.5
  optimizer: 'adam'
  iter: 2000
  alpha: 1.0
  id_cov: True
  acc_clustering: False
  tunable: False